### ISSUE TITLE
Checking robustness when spatial correction applied

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#14]
If we do an exponential correction to coexpression for head-head and tail-tail connections, do we still get similar results?

**Comment by AurinaBMH** [comment]
Exp fit fails if L/R neuron pairs are excluded- it can't fit an exponential. 
So we should eithher remove bin mean or avoid any corrections


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ben Fulcher <notifications@github.com> Date: 12/5/17  08:28  (GMT+02:00) To: AurinaBMH/WORMPlosCBtemplate <WORMPlosCBtemplate@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [AurinaBMH/WORMPlosCBtemplate] Checking robustness when spatial correction applied (#14) 
If we do an exponential correction to coexpression for head-head and tail-tail connections, do we still get similar results?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AurinaBMH/WORMPlosCBtemplate","title":"AurinaBMH/WORMPlosCBtemplate","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AurinaBMH/WORMPlosCBtemplate"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Checking robustness when spatial correction applied (#14)"}],"action":{"name":"View Issue","url":"https://github.com/AurinaBMH/WORMPlosCBtemplate/issues/14"}}}

**Comment by benfulcher** [comment]
I thought I was getting good exponential fits with L/R removed? The supp figure seems to still show decent exponential fits...?

**Comment by AurinaBMH** [comment]
There was an error fitting exp before (NaNs were not removed in coExp_corr = CoExpressionDistanceCorrect(C,G) function).
error fixed, so it fits exp now. 

Results with corrected coexpression still hold up. 
(the difference between connected vs unconnected links is however much smaller, p=10^-50 (for uncorrected) vs p=0.0068 (for corrected)). 
See evernote here:
Effect after exp distance correction <https://www.evernote.com/shard/s94/nl/2147483647/441ccc90-4192-4667-861c-02acf1c1c9c3/>

**Comment by benfulcher** [comment]
Yay! Strange it was getting errors since all of my plots fit exp no problem (I fixed this NaN issue back when I produced the figures on spatial dependences)...

**Comment by AurinaBMH** [comment]
We don't do spatial correction.
