### ISSUE TITLE
Rich versus nonrich??

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#17]
The Table S3 says commented in the .tex file:
> % rich feeder vs peripheral

But in the caption it says:
> Enrichment results for rich \textit{vs} all other (feed-in, feed-out, peripheral) links.
I assume it's actually rich/feeder versus peripheral? I remember rich on its own didn't have much statistical power...

**Comment by AurinaBMH** [comment]
In the last version I did enrichment on:

Rich vs all others (rich and feeder not combined) and on 
feed-in vs all others, 
feed-out vs all others separately. 

see evernote: RichFeeder vs Rich enrichment <https://www.evernote.com/shard/s94/nl/2147483647/e7f522e1-2b01-47a6-851b-ad511b4c1e07/> for top GO categories in rich vs rich&feeder. 

Hard to say which one is better, we get more power for rich&feeder combined, but is this a question we want to answer. 
Are we interested in similarity of neurons that connect to hubs or not really?

If we want to say what’s special about hub neurons, doing enrichment on only rich makes more sense. Especially when we then separately look at feed-in and feed-out. Combining rich (interneurons)+feeder (sensory+motor) is quite hard to justify in my mind now, because they differ in function so much and we can still get something when focusing on rich only.

**Comment by AurinaBMH** [comment]
Read through Alex's comments and decide on how to tell the story.

**Comment by AurinaBMH** [comment]
More power doing Rich&feeder together.
Main categories are the same, there are some differences: more metabolism and biosynthesis when feeders are included. 
But memory, and choline comes up for rich only. 

I think better to include both (rich&feeder vs peripheral). 
This is done in Table S5 nor and some changes made in the text accordingly.
