### ISSUE TITLE
Notation for contingency coefficient

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#2]
Alex suggests changing from r_\phi because of RC coeff (\phi), but this is standard.
What alternative. Maybe r_\rho??? @AurinaBMH ? Alex suggests r_\theta

**Comment by AurinaBMH** [comment]
It is called phi coefficient - we can not just change names because we have something with a similar (but not identical) name. 
I think we should keep r_\phi for coexpression,  and \Phi as well as \phi norm for RC. 
Or if we really want to avoid phi for coexpression, we could just use r (like correlation), but without additional letters, because it might confuse the reader.

**Comment by benfulcher** [comment]
Let's stick to r_\phi then
