### ISSUE TITLE
Why electrical > chemical?

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#82]
In discussion, we should comment on why electrical are more transcriptionally similar than chemical?? Maybe we mention that it's not a spatial effect -- distances are not greater for chemical synapses.
Can we get some insight into the genes involved that give us some hint? Is it expected that electrical synapses might be more stereotyped than chemical synapses (which may be more variable due to different neurotransmitters, etc.)?
Roger might have some input?

**Comment by AurinaBMH** [comment]
Gene scores for chemical VS electrical are not useful - all genes get very high p values because the majority of connections is chemical, so we'd need extremely high numbers of matches on mask to get lower p value. 
Gene scores for electrical VS chemical - can't explain this, but several genes on the top of the list are neurotransmitter related, others not specifically related to electrical transmission. 

Might be that it's not enough data to see the signal? could just speculate that's maybe due to the lack of neurotransmitter involvement? - should ask Roger as well.
